spring.application.name=tp8-monitoring
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoints.web.base-path=/actuator
management.info.env.enabled=true

# Informations personnalisées
info.app.name=Spring Monitoring App
info.app.version=1.0.0
info.app.description=TP8 - Supervision et Logging Spring Boot

server.port=8081

# Configuration du logging
logging.level.root=INFO
logging.level.ma.ens.tp8_monitoring=DEBUG
logging.file.name=logs/application.log
logging.pattern.console=%d{HH:mm:ss} [%t] %-5level %logger{36} - %msg%n

# Configuration Prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true